# Site-wide settings

title: "How Books Are Made"
tagline: "A podcast about the art and science of making books"
description: "Arthur Attwell speaks to book-making pioneers about design, production, marketing, distribution, and technology, and answers your questions. These are conversations for book lovers and publishing decision makers, whether you're crafting books at a big company or a boutique publisher."
image: "hbam-social.jpg"
url: "https://howbooksaremade.com"
google-analytics-id: "UA-27798626-7"
